### ISSUE TITLE
Parent Task Date

### ISSUE THREAD

**Issue by chaking22** [jsGanttImproved/jsgantt-improved#11]
Items with subtasks (identified as group = 1) don't appear to have their end dates recognized as the authoritative end date for that task.  Instead it appears that it takes the subtasks' furthest date as the end date.  

Is there a way around this behavior?  We have many nested tasks and some parents of subtasks should have dates further out than their subtasks.  Right now it appears we're limited in date to the last subtask's date.

**Comment by jsGanttImproved** [comment]
Fixed in commit 710ff11c7278104207028cfbd3a3904d475fc150

Dates specified on standard group tasks were always ignored in favour of a calculated range from the sub tasks.  

This commit will honour those date if they fall outside of that range. I.e. if the specified group start date was ``2016-01-01`` if the calculated start date was ``2016-05-14`` the  group start date will now be set at ``2016-01-01``. However if the calculated start date was ``2015-05-14`` the  group start date will still be set at ``2015-05-14`` as before.  End date is handled similarly.
