### ISSUE TITLE
Horizontal Scrollbars not always displaying

### ISSUE THREAD

**Issue by kevincam3** [jsGanttImproved/jsgantt-improved#148]
On the Mac 10.12, both Safari and Chrome did not show the scrollbar, initially. After hovering on it and playing around with the mouse, it could be made visible. This scrollbar in Safari and Chrome on the Mac 10.12 rides on top of the date numbers instead of displaying below the chart like it does in Windows/Edge.

I did see a scrollbar on an old Mac, but I think it's safe to assume that most users will not be on an old Mac with an unsupported browser.

I looked at preferences on the Mac to see if there was any "show/hide the scrollbar" option, but I didn't or couldn't find it, if it exists.

On all browsers I am still seeing a mismatch between the status dots. What are your thoughts regarding the mismatch between the status dots in the Gantt chart and the 2-column list?

**Comment by mariohmol** [comment]
hi.. could u figure that out?
what u did?

**Comment by kevincam3** [comment]
I didn't but my client is going to re-submit this issue using their account

**Comment by mariohmol** [comment]
does the demo works for u? https://jsganttimproved.github.io/jsgantt-improved/demo.html

**Comment by AMBrilliantfactory** [comment]
Hi,

I'm the client that Kevincam3 mentioned.  

I really like the JSGanttImproved.  I'm having some issues with it, though.  Could be a Mac issue.

Just to reiterate - the horizontal scrollbar does not appear immediately when viewing the Gantt chart on a Mac.  It has to be activated by hovering, and seems difficult to grab and drag.

Just now tried the horizontal scrolling in your demo, using a Mac OS X 10.12.  

Mac/Safari 12.0.3:  The scrollbar is difficult to activate.  Takes a long time of hovering and clicking to get the scrollbar to appear.  It displays over the top of the dates, making them harder to read.  The scrollbar is difficult to drag with the standard Mac wireless mouse (which has a trackpad top, instead of a wheel). 

Mac/Chrome (latest):  On hovering, the scrollbar activated right away, but after that if I click elsewhere in the page, the scrollbar does not deactivate (disappear).  Have to refresh the screen to get the scrollbar to disappear.  Like with Safari, the scrollbar displays over the bottom row of dates instead of below them, on Chrome.

PC Laptop/Edge: When I viewed your demo using a Windows 10 PC laptop with the Edge browser, the horizontal scrollbar appeared automatically without hovering first, and it displays below the chart instead of over the bottom row of dates.

So, the main issue is in how the horizontal scrollbar displays and performs on the Mac.

Is there a way to have the horizontal scrollbar display 100% of the time and below the chart (not over the dates) for Mac-based browsers?
![screen shot 2019-02-12 at 4 46 24 pm](https://user-images.githubusercontent.com/47575712/52670152-db1cd880-2ee5-11e9-95cf-33cf7f4b7778.png)

**Comment by mariohmol** [comment]
Hi.. thanks for that!

Are u using this link for testing?

https://jsganttimproved.github.io/jsgantt-improved/demo.html

I have mac as well.. its OS 10.14.1 and tested on FF/Chrome 71/Safari  12.0.1 .. its working very good.. 
I do zoom in/out and no problem at all.. 

really cant reproduce

**Comment by mariohmol** [comment]
The printscreen in home i did in this environment.. you can see how its the scroll here

https://github.com/jsGanttImproved/jsgantt-improved/raw/develop/docs/demo.gif

**Comment by AMBrilliantfactory** [comment]
Yes, I used the link you provided to see the demo.  

My version of Safari is 12.0.3 - newer than your version.

Then I would say that the scrollbar issue is appearing on a Mac OSX 10.12 but not on OSX 10.14.  

I was not trying to do a zoom in/out.  I was trying to scroll horizontally.

**Comment by mariohmol** [comment]
Can u try to update mac?

i had this working on version 10.12 .. i updated these days... 

is any plugin you have that is giving this behavior?

**Comment by AMBrilliantfactory** [comment]
I just found this with a quick web search...

On Macs with trackpads after OS X 10.7, there is a disappearing scrollbar by default.  They might have changed this after 10.12 but it is still present with this OS and earlier. 

https://stackoverflow.com/questions/7855590/preventing-scroll-bars-from-being-hidden-for-macos-trackpad-users-in-webkit-blin

The above discussion describes some custom CSS to fix this.

**Comment by mariohmol** [comment]
Can u try to add in your project and see if that fixes?

**Comment by AMBrilliantfactory** [comment]
The CSS solution from Stackoverflow.com appears to work to make the scrollbar visible below the chart, and now the scrollbar is easier to use on the Mac with the trackpad mouse.

**Comment by mariohmol** [comment]
included on 2.1.6 !

thanks for that!
