### ISSUE TITLE
Issue with dates timezone

### ISSUE THREAD

**Issue by Adrish-ASProg** [jsGanttImproved/jsgantt-improved#216]
When switching to "edit mode", dates in input are sometimes different than previous dates in label
This is caused by timezone not being always taken into account

Edit: You can see this on [demo page](https://jsganttimproved.github.io/jsgantt-improved/demo.html) if you're using specific GMT (mine is GMT +0200), just by enabling/disabling editable checkbox

I'll provide a PR to fix this today if I have some time to test that everything is working, otherwise tomorrow

Please note that I'm a young developer so double-check PR I made to ensure they won't cause any additional errors

**Comment by mariohmol** [comment]
Hi!

i did this and the dates here keeps the same.. and i'm at gmt + 3.. i dont know what is happening at your side

I've been checking the PR.. the comp and compval should have more checks (because one its like a number `30` and the other is `30%` .. so we could have something to check if is with % or not to save correctly.. 

but its ok .. what u did so far its making it better =)

if u want to discuss or show me something.. send an email to make a call..

thanks

**Comment by Adrish-ASProg** [comment]
Here's what I got on my side (look at Start/End dates), I'll check that tomorrow, I don't have time now but I know where this come from

![date](https://user-images.githubusercontent.com/43709217/60517399-eaa78d00-9cdf-11e9-8439-5f70382c8ea4.gif)

Glad to help, thanks to you and other contributors for providing this plugin :)

**Comment by Adrish-ASProg** [comment]
Problem was in draw file, `value = value ? value.toISOString().split('T')[0] : ''`.
This line convert the date to ISOString but ignore timezone, so a date like "03/07/2019 00:00" will be "02/07/2019 22:00" in my country, so one day backward

Replacing this with `value = value ? new Date(value.getTime() - (value.getTimezoneOffset() * 60000)).toISOString().split('T')[0] : '';`, should do the job as it adjust date according to timezone before conversion, see #217

**Comment by mariohmol** [comment]
AWESOME!!!!!!!

**Comment by mariohmol** [comment]
released on v2.2.8
