### ISSUE TITLE
what are the required configurations needed to properly display the gantt chart?

### ISSUE THREAD

**Issue by 3AUCE** [jsGanttImproved/jsgantt-improved#269]
the issues that im having is that the dates within the gantt chart (on the right) do not correspond to the dates that have been entered into the pStart/pEnd fields. i thought it was an issue within my data so i copied the JSON example data you have here (https://jsganttimproved.github.io/jsgantt-improved/fixes/data.json) and the issue remains. there is only one bar that displays on the right however, it extends from 1913 to 2019. am i missing a configuration setting or is this a known issue? how can i fix this?

**Comment by mariohmol** [comment]
isnt because of the pPlanStart and pPlanEnd dates?

**Comment by wmunsell** [comment]
the issue remains with/without pPlanStart and pPlanEnd dates populated. that's why i brought in the JSON data that is used within the your example. within your example it displays correctly, however, it does not display correctly when i bring the same data into my configuration. this is why i was thinking it had to be a configuration issue.

**Comment by mariohmol** [comment]
I see.. well.. maybe can u isolate this in a small project and submit in github or stackblitz for us?

**Comment by mariohmol** [comment]
as soon as u get the example please reopen this =)
