### ISSUE TITLE
Example in homepage is not working,TypeError: vDiv.nodeName is undefined

### ISSUE THREAD

**Issue by Pierminator** [jsGanttImproved/jsgantt-improved#33]
I follow section "Usage" in homepage, but it doesn't show anything, the error in console is : 
TypeError: vDiv.nodeName is undefined
JSGantt.GanttChart() jsgantt.js:1393
<anonymous> goToGantt_canvas:22
1 jsgantt.js:1393:1
![capture](https://cloud.githubusercontent.com/assets/5898466/23214379/ca289f64-f90e-11e6-8dfc-3e96a0d00ee8.PNG)

**Comment by eduardomourar** [comment]
@Pierminator, thanks. There was an error on the sample code when creating the gantt object:
```
var g = new JSGantt.GanttChart('g', document.getElementById('GanttChartDIV'), 'day');
```
Removed the old g parameter from the documentation wiki and the demo page too on commit [83d1f86](https://github.com/jsGanttImproved/jsgantt-improved/tree/83d1f8670a878786fdba3edb8342ae6eb4bd9ba8).

**Comment by seawasp2** [comment]
Hi,
I think the error is repeated further down the website in the "Putting all this information together the final code to produce the chart above is as follows:" section. The block of code contains...

 var g = new JSGantt.GanttChart('g',document.getElementById('GanttChartDIV'), 'day');

You guys have done a great job, thank you
C

**Comment by eduardomourar** [comment]
@seawasp2 , thanks! We have updated the website.

**Comment by seawasp2** [comment]
Hi,
Spotted another little typo on the website.
Under Usage, point 6, Method definition,
It still uses pColor instead of pClass

C.


On 27 May 2017 2:10 p.m., "Eduardo de Moura Rodrigues" <
notifications@github.com> wrote:

@seawasp2 <https://github.com/seawasp2> , thanks! We have updated the
website.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jsGanttImproved/jsgantt-improved/issues/33#issuecomment-304450856>,
or mute the thread

**Comment by eduardomourar** [comment]
Docs updated, thanks!
