### ISSUE TITLE
Problem generating image using html2canvas

### ISSUE THREAD

**Issue by Smartronic2017** [jsGanttImproved/jsgantt-improved#35]
Hello eveyone.
I have a problem with the generation of image of jsGantt
Using the instructions: 

var wg = Ext.get("GanttChartDIVchartTableh").getWidth();
var wd = Ext.get("GanttChartDIVglisthead").getWidth();

var element = document.getElementById('toPrint');

var scaleBy = 3;
//var w = element.scrollWidth - 300;
var w = wg + wd;
var h = element.scrollHeight - 30;
var div = document.querySelector('#toPrint');
var canvas = document.createElement('canvas');
canvas.width = w * scaleBy;
canvas.height = h * scaleBy;
canvas.style.width = w + 'px';
canvas.style.height = h + 'px';
var context = canvas.getContext('2d');
context.scale(scaleBy, scaleBy);

html2canvas(div, {
   canvas:canvas,
   onrendered: function (canvas) {

      //document.body.appendChild(canvas);

      //Canvas2Image.saveAsPNG(canvas);

      window.open(canvas.toDataURL('image/png'));

      //document.getElementById("canvas").remove();

      document.getElementById("toPrint").remove();
      me.setLoading(false);
   }
});

i can get the image of the gantt in high quality. But the image doesn't show the depends in the gantt.
Can someone help me?
@jsGanttImproved @RickCardoso @eduardomourar

**Comment by eduardomourar** [comment]
@Smartronic2017, I didn't investigate deep into the html2canvas, but its implementation is missing some of the DOM components from Gantt chart as you mentioned. I created this sample code using both [html2canvas](https://github.com/niklasvh/html2canvas) and [dom-to-image](https://github.com/tsayen/dom-to-image) here: [https://jsfiddle.net/eduardomourar/2gbp3wkk/](https://jsfiddle.net/eduardomourar/2gbp3wkk/)
So my suggestion is go with dom-to-image as you can see on the sample that the image is quite close to original HTML. Or open an issue with html2canvas, because it looks like a bug on their end.
Hope that helps
