### ISSUE TITLE
Overall percentage showing wrong value

### ISSUE THREAD

**Issue by mrahman32** [jsGanttImproved/jsgantt-improved#45]
If i have 4 sub task which completion values are 

- [ 100%, 50%, 50%, 50%] but  the parent percentage value showing 80%, but logically i know this should be 62.5% 
![1](https://user-images.githubusercontent.com/10150440/29747450-6e6c93a0-8b1d-11e7-8a65-7668b0754058.jpg)

**Comment by RickCardoso** [comment]
Dear @mrahman32,

the completion rate for parent tasks actually calculates it considering weighted (per number of days) child tasks. In your case, the calculation should be something like:

(100%*17 + 50%*6 + 50%*5.5 + 50%*1) / 29.5 = 80.17%

This is more logical and gives an overview of the project progress instead of the progress of a task list.

For now I'll close this item, but your feedback is very important and we'll keep in mind our users opinions on these features.

Thank you!

**Comment by sreemat1993** [comment]
@mariohmol  Can we override default overall percentage calculation.

**Comment by mariohmol** [comment]
Could u please provide an example json data where it calculates wrong?

**Comment by sreemat1993** [comment]
@mariohmol it not calculating wrong
I want to give my own percentage instead of the calculated

**Comment by mariohmol** [comment]
I see what u mean.. good idead.. check version 2.0.10 , you can set comp value in the data and this will be respected.. if you dont pass this will be calculated

**Comment by sreemat1993** [comment]
@mariohmol Thank you
