### ISSUE TITLE
Mistake in displaying data

### ISSUE THREAD

**Issue by mcomelli** [jsGanttImproved/jsgantt-improved#89]
There's a mistake in calculating tasks duration.
Little workaround:
-rounded to the last integer in js (which is not the solution, of course):

```
//if(Math.floor(tmpPer)!=tmpPer) tmpPer=Math.round(tmpPer*10)/10;
if(Math.floor(tmpPer)!=tmpPer) tmpPer=Math.round(tmpPer);
```
           
and changed padding and all 532px to 545px in css:

```
.gantt td { padding: 1px; }   /*padding from 0 to 1px*/
.glistgrid		{ width: 545px; }
.glistlbl		{ width: 545px; }
```

**Comment by benardt** [comment]
I had also an issue with duration tasks displaying. I found the issue was with the padding value in ".gantt td". I solved the issue by removing the class "gantt" in div container.

old container: <div style="position:relative" class="gantt" id="GanttChartDIV">
new container: <div style="position:relative" class="gantt" id="GanttChartDIV"></div>

**Comment by mariohmol** [comment]
Math round makes sense and the width has been changed as well! thanks
