### ISSUE TITLE
How can I add word-wrap to display the multi-line task Label (pName) ?

### ISSUE THREAD

**Issue by portalguru** [jsGanttImproved/jsgantt-improved#9]
I wanted to display the multi-line task label name on the gantt. Is there a option to apply word-wrap or any other way to achieve this?
-Guru.

**Comment by jsGanttImproved** [comment]
Sorry for the slow response.  I'm not sure what you are trying to do.

The task name is in the task list on the left at all times, are you trying to display it on the gantt itself or having problems because it is too long to fit in the existing box?

If it's the latter you will need to customise the css.  Look at the definitions of
```
.gtasklist
.gtaskname
```
as the most applicable but row height is a constant for all rows, you can't have one row a different height to all the others.

You will also need to adjust the setting ``setRowHeight()`` to match the css.

**Comment by craigefoster** [comment]
I found it best to just limit the number of characters painted for the task name. Noted alternatives require manipulating the row heights making the chart visually unappealing.

**Comment by eduardomourar** [comment]
I'm closing this, but will reopen if more information is given.
